# The `site.yml` blueprint defines the look of the start page (Dashboard) of the Panel.

# The site blueprint usually provides easy access to all main pages of the site.
# In this example blueprint, we also show subpages of the `photography` and `posts` pages.
# More about the site blueprint: https://getkirby.com/docs/reference/panel/blueprints/site

# The layout of this form has two columns:
columns:
  # The first column has one section for the subpages of the `photography` page in card layout
  # It reuses the pages section defined in `/site/blueprints/sections/albums.yml`
  - width: 1/2
    sections:
      albums: sections/albums

  # The second column has two sections, `posts` and `pages`
  - width: 1/2
    sections:
      # The `posts` section reuses the pages section defined in `/site/blueprints/sections/posts.yml`
      journals: sections/journals
      posts: sections/posts

      pages:
        type: pages
        create:
          - default
          - default.blocks
        templates:
          - about
          - home
          - default
          - default.blocks
      header:
        label: Header Images
        type: files
        uploads:
        template: image
